version: "3.9"
services:
  db:
    image: 'postgres:14.8-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web-shop:
    container_name: web-shop
    build:
      context: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  web-front:
    build:
      context: ../web-shop-front
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - web-shop
